// <auto-generated />
using System;
using AiNewsFeed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiNewsFeed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503084211_EnrichFeeds")]
    partial class EnrichFeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiNewsFeed.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MentionedCompanies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentionedModels")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FetchedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsRead");

                    b.HasIndex("MentionedModels");

                    b.HasIndex("PublishedAt")
                        .IsDescending();

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("AiNewsFeed.Models.FeedSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlwaysInclude")
                        .HasColumnType("bit");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FetchIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastFetchStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RequiredKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedUrl");

                    b.HasIndex("IsActive");

                    b.HasIndex("Priority");

                    b.HasIndex("Type");

                    b.ToTable("FeedSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.moonshot.cn/news/rss",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Moonshot AI (Kimi)",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.anthropic.com/blog/rss.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Anthropic Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://openai.com/blog/rss.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "OpenAI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://deepmind.google/discover/blog/rss.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google DeepMind Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://blog.google/technology/ai/rss/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google AI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://ai.meta.com/blog/rss/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Meta AI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://mistral.ai/news/rss.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Mistral AI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://cohere.com/blog/rss",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Cohere Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://stability.ai/blog/rss.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Stability AI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://blogs.nvidia.com/blog/category/artificial-intelligence/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "NVIDIA AI Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            AlwaysInclude = true,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://huggingface.co/blog/feed.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Hugging Face Blog",
                            Priority = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://bair.berkeley.edu/blog/feed.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "BAIR Blog (Berkeley)",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.microsoft.com/en-us/research/blog/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Microsoft Research",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://pytorch.org/blog/atom.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "PyTorch Blog",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://blog.tensorflow.org/feeds/posts/default",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "TensorFlow Blog",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://blog.langchain.dev/rss/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "LangChain Blog",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.technologyreview.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "MIT Technology Review",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,language model,Claude,GPT,Kimi,Gemini,Codex,OpenAI,Anthropic,Moonshot,DeepMind",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.wired.com/feed/tag/ai/latest/rss",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Wired - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "The Verge - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://venturebeat.com/category/ai/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "VentureBeat - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://techcrunch.com/category/artificial-intelligence/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "TechCrunch - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://arstechnica.com/tag/artificial-intelligence/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Ars Technica - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://spectrum.ieee.org/rss/topic/artificial-intelligence",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "IEEE Spectrum - AI",
                            Priority = 2,
                            RequiredKeywords = "AI,artificial intelligence,machine learning,LLM,Claude,GPT,Kimi,Gemini,Codex",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.artificialintelligence-news.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "AI News",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.marktechpost.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "MarkTechPost",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.unite.ai/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Unite.AI",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://machinelearningmastery.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Machine Learning Mastery",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://syncedreview.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Synced Review",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://analyticsindiamag.com/feed/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Analytics India Magazine",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://importai.substack.com/feed",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Import AI (Jack Clark)",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.deeplearning.ai/the-batch/rss/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "The Batch (DeepLearning.AI)",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.oneusefulthing.org/rss",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "One Useful Thing (Ethan Mollick)",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://lastweekin.ai/feed",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Last Week in AI",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://aiweekly.co/rss",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "AI Weekly",
                            Priority = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://lilianweng.github.io/index.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Lilian Weng",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://magazine.sebastianraschka.com/feed",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Sebastian Raschka",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://simonwillison.net/atom/everything/",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Simon Willison",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://huyenchip.com/feed.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Chip Huyen",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://eugeneyan.com/writing/feed.xml",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Eugene Yan",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://rss.arxiv.org/rss/cs.AI",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "ArXiv CS.AI",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://rss.arxiv.org/rss/cs.LG",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "ArXiv CS.LG",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://rss.arxiv.org/rss/cs.CL",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "ArXiv CS.CL",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://rss.arxiv.org/rss/cs.CV",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "ArXiv CS.CV",
                            Priority = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22Kimi+K2.6%22+OR+%22Moonshot+AI%22&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - Kimi K2.6",
                            Priority = 3,
                            Type = 5
                        },
                        new
                        {
                            Id = 45,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22Claude+Opus%22+OR+%22Claude+4.6%22+OR+%22Claude+4.7%22&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - Claude Opus",
                            Priority = 3,
                            Type = 5
                        },
                        new
                        {
                            Id = 46,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22Codex+5.5%22+OR+%22OpenAI+Codex%22&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - Codex",
                            Priority = 3,
                            Type = 5
                        },
                        new
                        {
                            Id = 47,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22GPT-5%22+OR+%22GPT-4.5%22+OR+%22OpenAI+o3%22&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - GPT-5",
                            Priority = 3,
                            Type = 5
                        },
                        new
                        {
                            Id = 48,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22Gemini+2.5%22+OR+%22Google+Gemini%22+model&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - Gemini",
                            Priority = 3,
                            Type = 5
                        },
                        new
                        {
                            Id = 49,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://news.google.com/rss/search?q=%22large+language+model%22+OR+%22LLM%22+release+announcement&hl=en-US&gl=US&ceid=US:en",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Google News - AI Models",
                            Priority = 2,
                            Type = 5
                        },
                        new
                        {
                            Id = 50,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.reddit.com/r/LocalLLaMA/.json?limit=25",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Reddit r/LocalLLaMA",
                            Priority = 2,
                            RequiredKeywords = "Kimi,Claude,Codex,GPT,Gemini,Moonshot,Anthropic,OpenAI",
                            Type = 2
                        },
                        new
                        {
                            Id = 51,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.reddit.com/r/MachineLearning/.json?limit=25",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Reddit r/MachineLearning",
                            Priority = 2,
                            RequiredKeywords = "Kimi,Claude,Codex,GPT,Gemini,Moonshot,Anthropic,OpenAI",
                            Type = 2
                        },
                        new
                        {
                            Id = 52,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.reddit.com/r/singularity/.json?limit=25",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "Reddit r/singularity",
                            Priority = 1,
                            RequiredKeywords = "Kimi,Claude,Codex,GPT,Gemini,Moonshot",
                            Type = 2
                        },
                        new
                        {
                            Id = 53,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://hn.algolia.com/api/v1/search?query=moonshot+ai+kimi&tags=story&hitsPerPage=30",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "HN - Kimi/Moonshot",
                            Priority = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 54,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://hn.algolia.com/api/v1/search?query=claude+opus+anthropic&tags=story&hitsPerPage=30",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "HN - Claude",
                            Priority = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 55,
                            AlwaysInclude = false,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://hn.algolia.com/api/v1/search?query=openai+codex+gpt&tags=story&hitsPerPage=30",
                            FetchIntervalMinutes = 60,
                            IsActive = true,
                            Name = "HN - OpenAI/Codex",
                            Priority = 3,
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
