// <auto-generated />
using System;
using AiNewsFeed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiNewsFeed.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiNewsFeed.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsRead");

                    b.HasIndex("PublishedAt")
                        .IsDescending();

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("AiNewsFeed.Models.FeedSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LastFetchStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FeedUrl");

                    b.HasIndex("IsActive");

                    b.ToTable("FeedSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.technologyreview.com/feed/",
                            IsActive = true,
                            Name = "MIT Technology Review"
                        },
                        new
                        {
                            Id = 2,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.wired.com/feed/tag/ai/latest/rss",
                            IsActive = true,
                            Name = "Wired - AI"
                        },
                        new
                        {
                            Id = 3,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
                            IsActive = true,
                            Name = "The Verge - AI"
                        },
                        new
                        {
                            Id = 4,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://venturebeat.com/category/ai/feed/",
                            IsActive = true,
                            Name = "VentureBeat - AI"
                        },
                        new
                        {
                            Id = 5,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://techcrunch.com/category/artificial-intelligence/feed/",
                            IsActive = true,
                            Name = "TechCrunch - AI"
                        },
                        new
                        {
                            Id = 6,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://arstechnica.com/tag/artificial-intelligence/feed/",
                            IsActive = true,
                            Name = "Ars Technica - AI"
                        },
                        new
                        {
                            Id = 7,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://spectrum.ieee.org/rss/topic/artificial-intelligence",
                            IsActive = true,
                            Name = "IEEE Spectrum - AI"
                        },
                        new
                        {
                            Id = 8,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://analyticsindiamag.com/feed/",
                            IsActive = true,
                            Name = "Analytics India Magazine"
                        },
                        new
                        {
                            Id = 9,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.artificialintelligence-news.com/feed/",
                            IsActive = true,
                            Name = "AI News"
                        },
                        new
                        {
                            Id = 10,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.marktechpost.com/feed/",
                            IsActive = true,
                            Name = "MarkTechPost"
                        },
                        new
                        {
                            Id = 11,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.unite.ai/feed/",
                            IsActive = true,
                            Name = "Unite.AI"
                        },
                        new
                        {
                            Id = 12,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://machinelearningmastery.com/feed/",
                            IsActive = true,
                            Name = "Machine Learning Mastery"
                        },
                        new
                        {
                            Id = 13,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://towardsdatascience.com/feed",
                            IsActive = true,
                            Name = "Towards Data Science"
                        },
                        new
                        {
                            Id = 14,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://ai.googleblog.com/feeds/posts/default",
                            IsActive = true,
                            Name = "Google AI Blog"
                        },
                        new
                        {
                            Id = 15,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://openai.com/blog/rss.xml",
                            IsActive = true,
                            Name = "OpenAI Blog"
                        },
                        new
                        {
                            Id = 16,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://deepmind.com/blog/feed/basic/",
                            IsActive = true,
                            Name = "DeepMind Blog"
                        },
                        new
                        {
                            Id = 17,
                            ConsecutiveFailures = 0,
                            FeedUrl = "https://www.microsoft.com/en-us/research/blog/feed/",
                            IsActive = true,
                            Name = "Microsoft Research"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
